name: Python Specification

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu
    strategy:
      matrix:
        py: [ "3.10", "pypy3.10" ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: "1.69.0"
            override: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Install Tox and any other packages
        run: "pip install 'tox>=4.11,<5' requests"

      - name: Download Geth and add to $PATH
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          $GITHUB_WORKSPACE/scripts/download_geth_linux.py --dir $GITHUB_WORKSPACE/bin
          echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH

      - name: Run Tox (CPython)
        if: "${{ !startsWith(matrix.py, 'pypy') }}"
        run: tox -e static
